# Generated by Django 3.1.5 on 2021-04-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('image', models.FileField(blank=True, null=True, upload_to='media', verbose_name='Files')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created_On')),
            ],
        ),
    ]
