# Generated by Django 3.1.5 on 2021-04-12 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_tutorial_published'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
